In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv('./patientsurvival.csv')
df

,encounter_id,patient_id,hospital_id,hospital_death,age,bmi,elective_surgery,ethnicity,gender,height,...,aids,cirrhosis,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,apache_3j_bodysystem,apache_2_bodysystem
0,66154,25312,118,0,68.0,22.730000,0,Caucasian,M,180.3,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Sepsis,Cardiovascular
1,114252,59342,81,0,77.0,27.420000,0,Caucasian,F,160.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Respiratory,Respiratory
2,119783,50777,118,0,25.0,31.950000,0,Caucasian,F,172.7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic
3,79267,46918,118,0,81.0,22.640000,1,Caucasian,F,165.1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular
4,92056,34377,33,0,19.0,NaN,0,Caucasian,M,188.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Trauma,Trauma
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91708,91592,78108,30,0,75.0,23.060250,0,Caucasian,M,177.8,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,Sepsis,Cardiovascular
91709,66119,13486,121,0,56.0,47.179671,0,Caucasian,F,183.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Sepsis,Cardiovascular
91710,8981,58179,195,0,48.0,27.236914,0,Caucasian,M,170.2,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic
91711,33776,120598,66,0,NaN,23.297481,0,Caucasian,F,154.9,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Respiratory,Respiratory
91712,1671,53612,104,0,82.0,22.031250,1,Caucasian,F,160.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Gastrointestinal,Gastrointestinal

In [3]:
null_list = list[df.isnull().sum()]

In [4]:
df1 = df
df1

,encounter_id,patient_id,hospital_id,hospital_death,age,bmi,elective_surgery,ethnicity,gender,height,...,aids,cirrhosis,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis,apache_3j_bodysystem,apache_2_bodysystem
0,66154,25312,118,0,68.0,22.730000,0,Caucasian,M,180.3,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Sepsis,Cardiovascular
1,114252,59342,81,0,77.0,27.420000,0,Caucasian,F,160.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Respiratory,Respiratory
2,119783,50777,118,0,25.0,31.950000,0,Caucasian,F,172.7,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic
3,79267,46918,118,0,81.0,22.640000,1,Caucasian,F,165.1,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Cardiovascular,Cardiovascular
4,92056,34377,33,0,19.0,NaN,0,Caucasian,M,188.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Trauma,Trauma
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91708,91592,78108,30,0,75.0,23.060250,0,Caucasian,M,177.8,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,Sepsis,Cardiovascular
91709,66119,13486,121,0,56.0,47.179671,0,Caucasian,F,183.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Sepsis,Cardiovascular
91710,8981,58179,195,0,48.0,27.236914,0,Caucasian,M,170.2,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,Metabolic,Metabolic
91711,33776,120598,66,0,NaN,23.297481,0,Caucasian,F,154.9,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Respiratory,Respiratory
91712,1671,53612,104,0,82.0,22.031250,1,Caucasian,F,160.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Gastrointestinal,Gastrointestinal

In [5]:
list_to_drop = ['encounter_id', 'hospital_id', 'patient_id', 'elective_surgery',
                'hospital_admit_source', 'icu_admit_source',
                'icu_id', 'icu_stay_type', 'icu_type', 'pre_icu_los_days',
                'readmission_status', 'albumin_apache', 'apache_2_diagnosis',
                'apache_3j_diagnosis', 'apache_post_operative', 'arf_apache',
                'bilirubin_apache', 'bun_apache', 'creatinine_apache', 'fio2_apache',
                'gcs_eyes_apache', 'gcs_motor_apache', 'gcs_unable_apache', 'gcs_verbal_apache',
                'glucose_apache', 'heart_rate_apache', 'hematocrit_apache' ,'intubated_apache',
                'map_apache', 'paco2_apache', 'paco2_for_ph_apache', 'pao2_apache',
                'ph_apache', 'resprate_apache', 'sodium_apache', 'temp_apache', 'urineoutput_apache',
                'ventilated_apache', 'wbc_apache', 'apache_4a_hospital_death_prob',
                'apache_4a_icu_death_prob', 'apache_3j_bodysystem', 'apache_2_bodysystem']

In [6]:
large_missing_values = df.isnull().sum()[df.isnull().sum() >= 27000]
len(large_missing_values)

74

In [7]:
new_df = df.drop(large_missing_values.index.tolist() + list_to_drop, axis = 1)
new_df

,hospital_death,age,bmi,ethnicity,gender,height,weight,d1_diasbp_max,d1_diasbp_min,d1_diasbp_noninvasive_max,...,d1_wbc_max,d1_wbc_min,aids,cirrhosis,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis
0,0,68.0,22.730000,Caucasian,M,180.3,73.9,68.0,37.0,68.0,...,14.10,14.10,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,0,77.0,27.420000,Caucasian,F,160.0,70.2,95.0,31.0,95.0,...,23.30,12.70,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0,25.0,31.950000,Caucasian,F,172.7,95.3,88.0,48.0,88.0,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0,81.0,22.640000,Caucasian,F,165.1,61.7,48.0,42.0,48.0,...,9.00,8.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0,19.0,NaN,Caucasian,M,188.0,NaN,99.0,57.0,99.0,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91708,0,75.0,23.060250,Caucasian,M,177.8,72.9,104.0,44.0,104.0,...,5.68,5.68,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
91709,0,56.0,47.179671,Caucasian,F,183.0,158.0,73.0,40.0,73.0,...,4.22,4.22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
91710,0,48.0,27.236914,Caucasian,M,170.2,78.9,77.0,49.0,77.0,...,17.55,17.55,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
91711,0,NaN,23.297481,Caucasian,F,154.9,55.9,99.0,32.0,99.0,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
91712,0,82.0,22.031250,Caucasian,F,160.0,56.4,47.0,32.0,47.0,...,24.40,24.40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [8]:
hyun_df = new_df.iloc[60000:80000,:]
hyun_df

,hospital_death,age,bmi,ethnicity,gender,height,weight,d1_diasbp_max,d1_diasbp_min,d1_diasbp_noninvasive_max,...,d1_wbc_max,d1_wbc_min,aids,cirrhosis,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis
60000,1,84.0,23.074256,Caucasian,M,180.3,75.01,122.0,32.0,122.0,...,13.57,12.94,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60001,0,55.0,22.142901,Caucasian,M,177.8,70.00,140.0,74.0,140.0,...,7.66,7.66,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60002,0,73.0,23.875711,Caucasian,F,172.7,71.21,63.0,43.0,63.0,...,26.05,26.05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60003,0,61.0,25.330852,Caucasian,F,172.7,75.55,154.0,13.0,154.0,...,19.56,19.56,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60004,0,75.0,28.744063,Caucasian,F,172.7,85.73,97.0,39.0,97.0,...,10.04,10.04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79995,1,71.0,21.822045,Caucasian,M,182.9,73.00,107.0,31.0,107.0,...,21.80,17.90,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
79996,0,79.0,31.550406,Caucasian,M,172.7,94.10,96.0,42.0,96.0,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
79997,0,65.0,27.771653,Caucasian,M,165.1,75.70,84.0,67.0,84.0,...,8.20,5.80,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
79998,1,89.0,31.684144,Caucasian,M,167.6,89.00,69.0,41.0,69.0,...,NaN,NaN,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
79999,1,NaN,28.148307,Caucasian,M,175.3,86.50,89.0,26.0,89.0,...,18.20,18.20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [9]:
hyun_df.isnull().sum()

hospital_death                   0
age                            988
bmi                            548
ethnicity                      528
gender                           3
                              ...
hepatic_failure                148
immunosuppression              148
leukemia                       148
lymphoma                       148
solid_tumor_with_metastasis    148
Length: 77, dtype: int64

In [10]:
hyun_df1 = hyun_df.fillna(hyun_df.mean())
hyun_df1_null = hyun_df1.isnull()

In [11]:
drop_list = pd.DataFrame(hyun_df1_null)
drop_list

,hospital_death,age,bmi,ethnicity,gender,height,weight,d1_diasbp_max,d1_diasbp_min,d1_diasbp_noninvasive_max,...,d1_wbc_max,d1_wbc_min,aids,cirrhosis,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis
60000,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
60001,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
60002,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
60003,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
60004,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79995,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
79996,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
79997,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
79998,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
79999,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [12]:
hyun_df2 = hyun_df1.dropna()
hyun_df2.isnull().sum().sum()
hyun_df2

,hospital_death,age,bmi,ethnicity,gender,height,weight,d1_diasbp_max,d1_diasbp_min,d1_diasbp_noninvasive_max,...,d1_wbc_max,d1_wbc_min,aids,cirrhosis,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis
60000,1,84.000000,23.074256,Caucasian,M,180.3,75.01,122.0,32.0,122.0,...,13.570000,12.940,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60001,0,55.000000,22.142901,Caucasian,M,177.8,70.00,140.0,74.0,140.0,...,7.660000,7.660,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60002,0,73.000000,23.875711,Caucasian,F,172.7,71.21,63.0,43.0,63.0,...,26.050000,26.050,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60003,0,61.000000,25.330852,Caucasian,F,172.7,75.55,154.0,13.0,154.0,...,19.560000,19.560,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60004,0,75.000000,28.744063,Caucasian,F,172.7,85.73,97.0,39.0,97.0,...,10.040000,10.040,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79995,1,71.000000,21.822045,Caucasian,M,182.9,73.00,107.0,31.0,107.0,...,21.800000,17.900,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
79996,0,79.000000,31.550406,Caucasian,M,172.7,94.10,96.0,42.0,96.0,...,12.474008,11.334,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
79997,0,65.000000,27.771653,Caucasian,M,165.1,75.70,84.0,67.0,84.0,...,8.200000,5.800,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
79998,1,89.000000,31.684144,Caucasian,M,167.6,89.00,69.0,41.0,69.0,...,12.474008,11.334,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
79999,1,62.304807,28.148307,Caucasian,M,175.3,86.50,89.0,26.0,89.0,...,18.200000,18.200,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [13]:
from sklearn.preprocessing import LabelEncoder

labels = hyun_df2[['gender']]
labels2 = hyun_df2[['ethnicity']]
encoder = LabelEncoder()
encoder.fit(labels)
oh_hyun_df = encoder.transform(labels)
encoder.fit(labels2)
oh_hyun_df2 = encoder.transform(labels2)

In [14]:
hyun_df = hyun_df2
hyun_df['gender'] = oh_hyun_df
hyun_df['ethnicity'] = oh_hyun_df2
hyun_df

,hospital_death,age,bmi,ethnicity,gender,height,weight,d1_diasbp_max,d1_diasbp_min,d1_diasbp_noninvasive_max,...,d1_wbc_max,d1_wbc_min,aids,cirrhosis,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis
60000,1,84.000000,23.074256,2,1,180.3,75.01,122.0,32.0,122.0,...,13.570000,12.940,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60001,0,55.000000,22.142901,2,1,177.8,70.00,140.0,74.0,140.0,...,7.660000,7.660,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60002,0,73.000000,23.875711,2,0,172.7,71.21,63.0,43.0,63.0,...,26.050000,26.050,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60003,0,61.000000,25.330852,2,0,172.7,75.55,154.0,13.0,154.0,...,19.560000,19.560,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
60004,0,75.000000,28.744063,2,0,172.7,85.73,97.0,39.0,97.0,...,10.040000,10.040,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79995,1,71.000000,21.822045,2,1,182.9,73.00,107.0,31.0,107.0,...,21.800000,17.900,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
79996,0,79.000000,31.550406,2,1,172.7,94.10,96.0,42.0,96.0,...,12.474008,11.334,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
79997,0,65.000000,27.771653,2,1,165.1,75.70,84.0,67.0,84.0,...,8.200000,5.800,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
79998,1,89.000000,31.684144,2,1,167.6,89.00,69.0,41.0,69.0,...,12.474008,11.334,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
79999,1,62.304807,28.148307,2,1,175.3,86.50,89.0,26.0,89.0,...,18.200000,18.200,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
hyun_df = hyun_df.astype({'ethnicity' : 'int64'})
hyun_df = hyun_df.astype({'gender' : 'int64'})
hyun_df.dtypes

hospital_death                   int64
age                            float64
bmi                            float64
ethnicity                        int64
gender                           int64
                                ...
hepatic_failure                float64
immunosuppression              float64
leukemia                       float64
lymphoma                       float64
solid_tumor_with_metastasis    float64
Length: 77, dtype: object

In [16]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, VotingClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_val_score, cross_validate, GridSearchCV
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier

In [17]:
y_hyun_df = hyun_df[['hospital_death']]
x_hyun_df = hyun_df.drop('hospital_death', axis=1)

x_train, x_test, y_train, y_test = train_test_split(x_hyun_df, y_hyun_df, test_size= 0.2, random_state=12 )

In [18]:
x_train

,age,bmi,ethnicity,gender,height,weight,d1_diasbp_max,d1_diasbp_min,d1_diasbp_noninvasive_max,d1_diasbp_noninvasive_min,...,d1_wbc_max,d1_wbc_min,aids,cirrhosis,diabetes_mellitus,hepatic_failure,immunosuppression,leukemia,lymphoma,solid_tumor_with_metastasis
73219,76.000000,26.171875,2,0,160.0,67.0,84.0,74.0,84.0,74.0,...,13.200000,13.200,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
69094,58.000000,28.423761,5,0,154.9,68.2,96.0,76.0,96.0,76.0,...,13.200000,13.200,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
61962,40.000000,26.020761,2,0,170.0,75.2,99.0,74.0,99.0,74.0,...,12.474008,11.334,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
71584,69.000000,33.286151,2,0,167.6,93.5,70.0,61.0,70.0,61.0,...,16.500000,12.000,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
71846,53.000000,21.920710,2,1,170.2,63.5,83.0,56.0,83.0,56.0,...,2.800000,2.800,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69623,62.304807,25.306173,2,1,177.8,80.0,63.0,56.0,63.0,56.0,...,7.500000,7.500,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
63788,73.000000,49.483778,2,0,173.0,148.1,96.0,33.0,96.0,33.0,...,13.180000,11.100,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
67556,32.000000,27.994954,2,1,177.8,88.5,101.0,90.0,101.0,90.0,...,12.474008,11.334,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
65901,51.000000,63.020408,2,1,175.0,186.0,99.0,68.0,99.0,68.0,...,14.630000,14.630,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
74307,80.000000,30.387053,2,1,188.0,107.4,59.0,51.0,59.0,51.0,...,15.700000,12.400,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
x_test.dtypes

age                            float64
bmi                            float64
ethnicity                        int64
gender                           int64
height                         float64
                                ...
hepatic_failure                float64
immunosuppression              float64
leukemia                       float64
lymphoma                       float64
solid_tumor_with_metastasis    float64
Length: 76, dtype: object

In [20]:
y_train.dtypes

hospital_death    int64
dtype: object

In [21]:
dt_clf = DecisionTreeClassifier(random_state=12)
rf_clf = RandomForestClassifier(random_state=12)
lr_clf = LogisticRegression(random_state=12)
knn_clf = KNeighborsClassifier(n_neighbors=8)
vo_clf = VotingClassifier(estimators=[('LR',lr_clf),('KNN',knn_clf)], voting='soft')
gb_clf = GradientBoostingClassifier(random_state=12)

In [22]:
dt_clf.fit(x_train, y_train)
dt_pred = dt_clf.predict(x_test)
print('DecisionTreeClassifier 정확도 : {0:.4f}'.format(accuracy_score(y_test, dt_pred)))
rf_clf.fit(x_train, y_train)
rf_pred = rf_clf.predict(x_test)
print('RandomForestClassifier 정확도 : {0:.4f}'.format(accuracy_score(y_test, rf_pred)))
lr_clf.fit(x_train, y_train)
lr_pred = lr_clf.predict(x_test)
print('LogisticRegression 정확도 : {0:.4f}'.format(accuracy_score(y_test, lr_pred)))
vo_clf.fit(x_train, y_train)
vo_pred = vo_clf.predict(x_test)
print('VotingClassifier 정확도 : {0:.4f}'.format(accuracy_score(y_test, vo_pred)))
knn_clf.fit(x_train, y_train)
knn_pred = knn_clf.predict(x_test)
print('KNeighborsClassifier 정확도 : {0:.4f}'.format(accuracy_score(y_test, knn_pred)))
gb_clf.fit(x_train, y_train)
gb_pred = gb_clf.predict(x_test)
print('GradientBoostingClassifier 정확도 : {0:.4f}'.format(accuracy_score(y_test, gb_pred)))

DecisionTreeClassifier 정확도 : 0.8709
RandomForestClassifier 정확도 : 0.9281
LogisticRegression 정확도 : 0.9227
VotingClassifier 정확도 : 0.9230
KNeighborsClassifier 정확도 : 0.9217
GradientBoostingClassifier 정확도 : 0.9291

In [23]:
scores = cross_val_score(gb_clf, x_hyun_df, y_hyun_df, scoring='accuracy', cv=5)
print('교차 검증별 정확도 : ',np.round(scores, 4))
print('평균 검증 정확도', np.round(np.mean(scores), 4))

교차 검증별 정확도 :  [0.9304 0.924  0.9258 0.9253 0.9242]
평균 검증 정확도 0.9259

In [24]:
dtree = DecisionTreeClassifier()
params = {'max_depth':[1,2,3,4], 'min_samples_split':[2,3,4]}
grid_dtree = GridSearchCV(dtree, param_grid = params, cv=5, refit=True)
grid_dtree.fit(x_train, y_train)

scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params','mean_test_score','rank_test_score','split0_test_score',
          'split1_test_score','split2_test_score','split3_test_score']]

,params,mean_test_score,rank_test_score,split0_test_score,split1_test_score,split2_test_score,split3_test_score
0,"{'max_depth': 1, 'min_samples_split': 2}",0.917828,10,0.917843,0.917843,0.917817,0.917817
1,"{'max_depth': 1, 'min_samples_split': 3}",0.917828,10,0.917843,0.917843,0.917817,0.917817
2,"{'max_depth': 1, 'min_samples_split': 4}",0.917828,10,0.917843,0.917843,0.917817,0.917817
3,"{'max_depth': 2, 'min_samples_split': 2}",0.919304,7,0.919448,0.919127,0.920064,0.915891
4,"{'max_depth': 2, 'min_samples_split': 3}",0.919304,7,0.919448,0.919127,0.920064,0.915891
5,"{'max_depth': 2, 'min_samples_split': 4}",0.919304,7,0.919448,0.919127,0.920064,0.915891
6,"{'max_depth': 3, 'min_samples_split': 2}",0.921166,1,0.918485,0.921694,0.919422,0.921027
7,"{'max_depth': 3, 'min_samples_split': 3}",0.921166,1,0.918485,0.921694,0.919422,0.921027
8,"{'max_depth': 3, 'min_samples_split': 4}",0.921166,1,0.918485,0.921694,0.919422,0.921027
9,"{'max_depth': 4, 'min_samples_split': 2}",0.920781,4,0.918164,0.920411,0.921669,0.919422
10,"{'max_depth': 4, 'min_samples_split': 3}",0.920781,4,0.918164,0.920411,0.921669,0.919422
11,"{'max_depth': 4, 'min_samples_split': 4}",0.920781,4,0.918164,0.920411,0.921669,0.919422